sudo: required
services:
  - docker

before_install:
  - docker build -t sangw0804/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sangw0804/multi-client-test npm run test

after_success:
  - docker build -t sangw0804/multi-client ./client
  - docker build -t sangw0804/multi-nginx ./nginx
  - docker build -t sangw0804/multi-server ./server
  - docker build -t sangw0804/multi-worker ./worker
  # login dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to dockerhub
  - docker push sangw0804/multi-client
  - docker push sangw0804/multi-nginx
  - docker push sangw0804/multi-server
  - docker push sangw0804/multi-worker